### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by edge** [KanColleTool/kcsrv#6]
@uppfinnarn 

I'd love to contribute to this project, but I don't know where to start.

Can you provide a short introduction of the code and your development practices in the README?

**Comment by SoftwareGuy** [comment]
At the moment I don't know where @uppfinnarn is. He's MIA. Tried to contact him, but he seems to either be busy with RL work or something.

The biggest thing I did was just get dirty with the code. I had the VM running with the server up, and then I was watching the KanColle flash files access endpoints that are currently programmed in. I did, however, fork the project and use the knowledge to build a PHP version of the server software. DMM uses PHP themselves, so it was just a matter of mimicking DMM's setup.

Once I understood the basics, I coded up a crude system that allowed one to hack in ships and everything needed to get to the dashboard. The biggest part of trying to break apart the game is how to do the RNG, and also equipment - How is that value done? Is it applied on top of the girl's base stats? Or does it directly modify the base values in the DB?. I also got construction working... where the server takes your reserves and eats it. Gotta keep Akagi in the server room happy, you know?

My PHP implementation is very crappily done and I am in no position to really open source my version, I might at some point but at the moment I'm busy with other things. As for @uppfinnarn... Where in the world is he?

**Comment by uppfinnarn** [comment]
I'm right here, and drowning in work. There seems to be some decent interest for this though, so I should try poking around with it again when I have time for it again.

The project layout should be fairly straightforward if you're familiar with web development in general (maybe not so much if all you've done is cobble together PHP scripts without a proper router), with endpoints split into Blueprints (sub-routers, basically) for organization. [Flask's documentation](http://flask.pocoo.org/) is your friend. I could move it to Django if people would prefer that; I can work with both no problem - Django would involve more boilerplate, but perhaps more organized code. I'm not sure.

The only nonstandard things that are used extensively are `svdata()`, which just returns a `svdata=`-prefixed JSON response, like the game expects it, `prepare_api_blueprint()`, which makes `403`s behave as expected (triggering an errorcat instead of a freeze), and `get_token_admiral_or_error()`, which returns the authenticating admiral, or throws a `403 Unauthorized` error if the token is invalid.

**Comment by edge** [comment]
Yeah, I'm a Node.js developer, so I'm pretty comfortable with the layout. @SoftwareGuy basically removed my doubts. I was afraid that I was going to have to decompile the Flash.

I'll start playing around with the code.

**Comment by edge** [comment]
So I've started weaving through the code, and I basically understand what is going on. At this point I can probably work out a lot of the backend functionality.

The server doesn't seem to be picking any API requests from the flash, though, so I can't really do much. Any comment?

**Comment by uppfinnarn** [comment]
Huh, that's strange, the game should contact whatever server it's loaded from, unless they recently changed that. Are you sure your changes are picked up? Is nothing logged in the console?

If you're running the development server (`./kcsrv.py`, access on `:5000` or whatever you choose), it should autoreload (and print a console message every time you change the code). For the uwsgi production setup, it will not autoreload unless you `touch kcsrv.py` manually.

If it really doesn't contact the backend server, please check the network panel to see where it's going instead, because then there's something wrong :/

**Comment by edge** [comment]
There was a game update recently, after the Winter event. Although I doubt that's relevant.

Apparently it doesn't work when using the host bridge. I changed to 192.168.33.10:5000 and now it at least requests Core.swf, but it stops there and hangs.

**Comment by uppfinnarn** [comment]
This sounds familiar, but I can't remember what I did to fix it… can you open it in a private window and run it with the network panel open? It could be as simple as it hitting an unimplemented endpoint.

**Comment by SoftwareGuy** [comment]
Do note that KC is hardcoded to look for data files in http://IP/kcs for retarded reasons. Even if you have the game in say http://IP/kantcolle .

**Comment by uppfinnarn** [comment]
No, it assumes the whole game is mounted on the root of the domain, not /kcs. API calls are done to /kcsapi, etc.

**Comment by SoftwareGuy** [comment]
Alright, I guess that works. If I can find the 7zip archive I sent @uppfinnarn I might throw it into my own repo for us to pick at. It was a Xmas project and well, i'm bored after work and I don't feel like playing shooters, so I might as well manage my fleets.

I need to boot the game up from DMM again to get the latest KC api_start2 updates and such. I have my PHP KC Assets Downloader script that I will likely put in a repo of it's own for easy asset leeching, although I need to look at the audio assets - some of the ships don't have hourlies, but some do, so i might set a ship that has houriles as my DMM secretary and see what MP3 they are downloading. Then it'll just be a matter of finding the last MP3 file of all the voices and downloading every MP3 until hitting that number.

**Comment by SoftwareGuy** [comment]
@uppfinnarn @edge 
I've upped my scripts (see the kcdownloaders repo in my profile) to give you guys a hand with asset downloading. Feed the script(s) a current api_start2 and you'll be set.

Most scripts are PHP + cURL extension. Don't shoot me... :expressionless:

That should help stop a lot of 404s and/or errorcats if you're manually tinkering around.
