### ISSUE TITLE
Asset Downloading Scripts

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#9]
Alright, trying to not toot my own trumpet here, but I thought I'd mention it. Is it possible to sticky this?

To successfully run this project, and any of the other developer forks, you will need the game assets. To cut down on size, we try not to include everything but the essential SWFs - however this may not be enough to satisfy the game client.

This is where [my script](https://github.com/SoftwareGuy/kcdownloaders/blob/master/kcdownloader2.py) comes in. I coded it in Python3 and it's currently sitting in my repo. It will download everything apart from titlecalls, furniture items and character voices.

By using the script, you'll get always up to date assets. Just make sure your api_start2.json is fresh (best to obtain this though KCT and poke through it's cache for that).

**Comment by SunDwarf** [comment]
If you don't mind, I'll merge this into my fork later today, seems useful.

**Comment by uppfinnarn** [comment]
I'd be happy to merge a PR with this. I'd probably put it in a [Flask-Script command](http://flask-script.readthedocs.org/en/latest/) though - that way, you can do `./cmd.py updateassets` or something like that, rather than having a bunch of scripts scattered around the project root.

Also, you may want to change it to use [requests](http://docs.python-requests.org/en/latest/) rather than PyCurl, as Requests is pretty much the de-facto standard for fetching stuff off the internet, and makes the code a whole lot shorter.

That could also be put into the project's `requirements.txt`, since it'll probably be useful elsewhere too - just enter the virtualenv (`. bin/activate`), run `pip install requests` and `pip freeze > requirements.txt` to update it.

---

While it's not really a problem, there's also quite a bit of boilerplate in here that could be eliminated. Written off the top of my head (not tested):

```python
# This eliminates the need to stand in the right directory, by basing it off the script path
# Will need to be adjusted if in a Flask-Script command, since it will point to *this* file, not
# the main file. So, ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')) or
# something of the sort
ROOT = os.path.abspath(os.path.dirname(__file__))

# ...

sources = [
    ['kcs', ['Core.swf', 'mainD2.swf', 'etc']],
    ['kcs/resources/swf', ['commonAssets.swf', 'etc']],
]
for path, files in sources:
    for file in files:
        filepath = os.path.join(path, file)
        url = "http://123.456.78.9/{0}".format(filepath)
        dest = os.path.join(ROOT, filepath)
        
        print("Downloading {0}...".format(filepath))
        # Do something to download `url` to `dest`
```

**Comment by SunDwarf** [comment]
I converted it into a manager command. I can't submit a PR because the codebases are completely incompatible, but i'll just copy the links here:

[kcdownloader2.py](https://github.com/SunDwarf/kcsrv/blob/master/commands/kcdownloader2.py)
[manage.py](https://github.com/SunDwarf/kcsrv/blob/master/manage.py)

**Comment by uppfinnarn** [comment]
I'd gladly make yours the main codebase and add you as a contributor tbh, I'm too busy to actively work on this, but I'd gladly oversee it.

**Comment by SunDwarf** [comment]
That's be great, but I despise docker/vagrant stuff, so if you do just be warned I will kill it with fire.

**Comment by uppfinnarn** [comment]
Huh, why Vagrant? It's just a convenient way to make a VM from a template image.

**Comment by SunDwarf** [comment]
2hard4me
I just prefer running an SSH tunnel and a virtualenv

**Comment by uppfinnarn** [comment]
Whatever floats your boat =w=

Invited you to the organization, merge your tree into this repo and close this when you're done
